# Generated by Django 4.2.30 on 2026-06-06 11:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_unit_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='number_of_bathrooms',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='number_of_rooms',
        ),
        migrations.AddField(
            model_name='unit',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last updated'),
        ),
        migrations.AlterField(
            model_name='client',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='type',
            field=models.CharField(choices=[('A', 'Apartment'), ('P', 'Penthouse'), ('V', 'Villa')], default='A', max_length=200),
        ),
        migrations.CreateModel(
            name='Bedroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master', models.BooleanField(default=False)),
                ('bed_type', models.CharField(default='', max_length=200)),
                ('bed_number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last updated')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Bathroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathroom_type', models.CharField(choices=[('F', 'Full'), ('H', 'Half')], default='F', max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last updated')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.unit')),
            ],
        ),
    ]
