# Generated by Django 4.2.30 on 2026-06-06 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_unit_number_of_bathrooms_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bedroom',
            old_name='bed_number',
            new_name='number_of_beds',
        ),
    ]
