# Generated by Django 4.2.30 on 2026-06-06 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_rename_bed_number_bedroom_number_of_beds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bedroom',
            old_name='master',
            new_name='master_bedroom',
        ),
    ]
