# Generated by Django 4.2.30 on 2026-06-06 11:52

import backend.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_rename_master_bedroom_master_bedroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedroomPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.BooleanField(default=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(upload_to=backend.models.BedroomPhoto.generate_upload_path)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last updated')),
                ('bedroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.bedroom')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.unit')),
            ],
        ),
    ]
