# Generated by Django 4.2.30 on 2026-06-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_bedroomphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedroomphoto',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
