# Generated by Django 4.2.30 on 2026-06-06 11:58

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_bedroomphoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedroomphoto',
            name='image',
            field=models.ImageField(upload_to=backend.models.BedroomPhoto.generate_upload_path),
        ),
    ]
