# Generated by Django 4.2.30 on 2026-06-06 12:38

import backend.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_bedroomphoto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='thumbnail',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='UnitPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.BooleanField(default=True)),
                ('thumbnail', models.BooleanField(default=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=200)),
                ('category', models.CharField(choices=[('L', 'Living'), ('K', 'Kitchen'), ('B', 'Balcony'), ('G', 'Garden')], default='L', max_length=200)),
                ('image', models.ImageField(upload_to=backend.models.UnitPhoto.generate_upload_path)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last updated')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.unit')),
            ],
        ),
    ]
