# Generated by Django 4.2.30 on 2026-06-06 19:22

import backend.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_unit_thumbnail_unitphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='type',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('Penthouse', 'Penthouse'), ('Villa', 'Villa')], default='Apartment', max_length=200),
        ),
        migrations.AlterField(
            model_name='unitphoto',
            name='category',
            field=models.CharField(choices=[('Living', 'Living'), ('Kitchen', 'Kitchen'), ('Balcony', 'Balcony'), ('Garden', 'Garden')], default='Living', max_length=200),
        ),
        migrations.CreateModel(
            name='BathroomPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.BooleanField(default=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(upload_to=backend.models.BathroomPhoto.generate_upload_path)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last updated')),
                ('bathroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.bathroom')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.unit')),
            ],
        ),
    ]
