# Generated by Django 4.2.30 on 2026-06-06 21:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_unit_type_alter_unitphoto_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='booking',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last updated'),
        ),
        migrations.AlterField(
            model_name='bathroom',
            name='bathroom_type',
            field=models.CharField(choices=[('Full', 'Full'), ('Half', 'Half')], default='Full', max_length=200),
        ),
    ]
