# Generated by Django 4.2.30 on 2026-06-07 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_booking_created_date_booking_last_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='registration_date',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='client',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last updated'),
        ),
    ]
