# Generated by Django 4.2.30 on 2026-06-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_rename_registration_date_client_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='card_cvc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='card_expiry',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='card_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='card_number',
            field=models.CharField(default='', max_length=200),
        ),
    ]
