# Generated by Django 4.2.30 on 2026-06-09 00:16

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_booking_card_cvc_booking_card_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitphoto',
            name='image',
            field=models.ImageField(blank=True, upload_to=backend.models.UnitPhoto.generate_upload_path),
        ),
    ]
