apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: booking
  template:
    metadata:
      labels:
        app: booking
    spec:
      containers:
        - image: public.ecr.aws/l6m2t8p7/docker-2048:latest
          name: booking
          ports:
            - containerPort: 80
